name: FastAPI on Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image from FastAPI
      run: docker build -t ${{ secrets.Docker_username }}/fastapi-docker:${{ github.sha }} .

    - name: Logging into Docker Hub
      run: docker login --username ${{ secrets.Docker_username }} --password-stdin <<< ${{ secrets.Docker_password }}

    - name: Push the image to Docker Hub
      run: docker push ${{ secrets.Docker_username }}/fastapi-docker:${{ github.sha }}
